- name: Adds ondrej repos
  apt_repository:
    repo: "ppa:ondrej/php"
    update_cache: yes
- name: Installs php7-fpm
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  notify:
    - Restart php7-fpm
  with_items:
    - php7-fpm
    - composer
    - php-apcu
    - php-pear
    - php{{ php7_version }}-bz2
    - php{{ php7_version }}-cli
    - php{{ php7_version }}-curl
    - php{{ php7_version }}-gd
    - php{{ php7_version }}-intl
    - php{{ php7_version }}-mbstring
    - php{{ php7_version }}-mcrypt
    - php{{ php7_version }}-mysql
    - php{{ php7_version }}-opcache
    - php{{ php7_version }}-readline
    - php{{ php7_version }}-xml
    - php{{ php7_version }}-zip
    - "[{{ php7_module_debs }}]"

