- name: Install Python package manager
  apt: name=python3-pip state=present
  when: ansible_lsb.major_release|int >= 16
- name: install python mysql bindings
  apt: name=python-mysqldb state=installed
  become: yes
  become_method: sudo
- name: Install packages required for ansible mysql modules
  apt: name={{ item }} state=present
  with_items:
    - python-mysqldb
  when: ansible_lsb.major_release|int < 16

- name: Install packages required for ansible mysql modules
  apt: name={{ item }} state=present
  with_items:
    - python3-dev
    - libmysqlclient-dev
  when: ansible_lsb.major_release|int >= 16

- name: Update mysql root password for all root accounts "{{ dbpass }}"
  mysql_user: name=root password=1234 priv="*.*:ALL,GRANT"

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
