---
- name: wait for ssh
  hosts: localhost
  gather_facts: no

  tasks:
    - local_action: wait_for port=22 host="{{ ip }}" search_regex=OpenSSH delay=10
- hosts: all
  become: true
  vars:
    document_root: /vagrant
    www_user: vagrant
    www_group: vagrant
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600
  roles:
    - main
    - nginx
    - mysql
    - php
    - php-fpm
